#!/bin/env bash

### This is sourced by wine-launch/launch-app.sh. It serves the same purpose as sommelier's snapcraft.yaml.

export APP_SHARE_DIR="$PWD"

export TRICKS="corefonts fontsmooth=rgb vcrun2019 dotnet48" 
#export INSTALL_FLAGS="/passive" # /qn for silent (MSI)

# Set WINE environment variables.
export WINEARCH="win32" # won't work: ffmpeg binaries are 64-bit
# export WINEARCH="win64"
export WINEDLLOVERRIDES="mscoree=n;mshtml=" # avoids gecko and mono prompts
export WINELOADER="/snap/wine-platform-7-stable-core20/current/opt/wine-stable/bin/wine"
# export WINETRICKS="/snap/wine-platform-runtime-core20/current/bin/winetricks"
export WINETRICKS_LATEST_VERSION_CHECK='disabled'
export WINEPREFIX="${APP_SHARE_DIR}/.wine"

# Set wine-launch environment variables.
# export INSTALL_EXE="$(xdg-user-dir DOWNLOAD)/SayMoreInstaller.3.5.1.msi"
export INSTALL_EXE="${APP_SHARE_DIR}/data/Setup OneStoryEditor_5.1.4_x86.exe"
# export RUN_EXE="${WINEPREFIX}/drive_c/Program Files (x86)/SIL/OneStory Editor/StoryEditor.exe"
export RUN_EXE="${WINEPREFIX}/drive_c/Program Files/SIL/OneStory Editor/StoryEditor.exe"
